// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polaris.Conteiner.Context;

#nullable disable

namespace Polaris.Conteiner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Polaris.Conteiner.Models.CategoriaConteiner", b =>
                {
                    b.Property<int>("CategoriaConteinerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("CategoriaConteinerUuid")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ConteinerId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoriaConteinerId");

                    b.HasIndex("ConteinerId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CategoriasConteineres");
                });

            modelBuilder.Entity("Polaris.Conteiner.Models.Conteiner", b =>
                {
                    b.Property<int>("ConteinerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<Guid>("ConteinerUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fabricacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ConteinerId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Conteiner");
                });

            modelBuilder.Entity("Polaris.Conteiner.Models.TipoConteiner", b =>
                {
                    b.Property<int>("TipoConteineroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Altura")
                        .HasColumnType("double");

                    b.Property<double>("Comprimento")
                        .HasColumnType("double");

                    b.Property<int?>("ConteinerId")
                        .HasColumnType("int");

                    b.Property<double>("Largura")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("PesoMaximo")
                        .HasColumnType("double");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TipoConteinerUuid")
                        .HasColumnType("char(36)");

                    b.Property<double>("ValorDiaria")
                        .HasColumnType("double");

                    b.Property<double>("ValorMensal")
                        .HasColumnType("double");

                    b.Property<double>("Volume")
                        .HasColumnType("double");

                    b.HasKey("TipoConteineroId");

                    b.HasIndex("ConteinerId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposConteineres");
                });

            modelBuilder.Entity("Polaris.Conteiner.Models.CategoriaConteiner", b =>
                {
                    b.HasOne("Polaris.Conteiner.Models.Conteiner", null)
                        .WithMany("CategoriasConteineres")
                        .HasForeignKey("ConteinerId");
                });

            modelBuilder.Entity("Polaris.Conteiner.Models.TipoConteiner", b =>
                {
                    b.HasOne("Polaris.Conteiner.Models.Conteiner", null)
                        .WithMany("TiposConteineres")
                        .HasForeignKey("ConteinerId");
                });

            modelBuilder.Entity("Polaris.Conteiner.Models.Conteiner", b =>
                {
                    b.Navigation("CategoriasConteineres");

                    b.Navigation("TiposConteineres");
                });
#pragma warning restore 612, 618
        }
    }
}
